<?php
/**
 * @file /var/www/jeff.git/themes/default/view/manage_table.php
 * @ingroup default_theme backoffice
 * @brief Template for the autogenerated @ref backoffice wrapper (items list and forms are wrapped in this template) 
 *
 * Available variables:
 * - **title**: section title
 * - **text**: (optional) information text
 * - **table**: backoffice content (list, insertion form, modification form, ...)
 *
 * @author abidibo abidibo@gmail.com
 * @version 0.99
 * @date 2011-2012
 * @copyright Otto srl [MIT License](http://www.opensource.org/licenses/mit-license.php)
 */
?>
<section>
<h1 class="section_title"><?= $title ?></h1>
<? if(isset($text)): ?>
<p><?= $text ?></p>
<? endif ?>
<?= $table ?>
</section>
